	\context ChordNames
		\chords {
		\set Score.markFormatter = #format-mark-box-numbers

		% 1 intro
		\mark \default
		\skip 1*8

		% 2 estrofa 1
		\mark \default
		\skip 1*8

		% 3 estrofa 2
		\mark \default
		\skip 1*9

		% 4 coro 1
		\mark \default
		\skip 1*9

		% 5 coro 2
		\mark \default
		\skip 1*9

		% 6 estrofa 3
		\mark \default
		\skip 1*8

		% 7 estrofa 4
		\mark \default
		\skip 1*9

		% 8 coro 3
		\mark \default
		\skip 1*9

		% 9 coro 4
		\mark \default
		\skip 1*9

		% 10 puente
		\mark \default
		\skip 1*5

		% 11 coro 5
		\mark \default
		\skip 1*9

		% 12 coro 6
		\mark \default
		\skip 1*9

		% 13 finale
		\mark \default
		}
