\context ChordNames
	\chords {
		\set majorSevenSymbol = \markup { "maj7" }
		\set chordChanges = ##t
		% intro
		a2 a2
		a2 e2 fis2:m cis2:m7
		d2 d2:m a2 e2
		e2

		% estrofa 1
		a2 e2 fis2:m cis2:m7
		d2 b2:m g2 e2

		% estrofa 2
		a2 e2 fis2:m cis2:m7
		d2 b2:m g2 e2
		e2

		R1

		% coro 1
		a1 e1 fis1:m cis1:m7
		d1 d1 a1 e1
		e1

		% coro 2
		a1 e1 fis1:m cis1:m7
		d1 d1 a1 e1
		e1

		% interludio
		a1 e1 fis1:m cis1:m7
		d1 d1:m a1 e1

		% estrofa 3
		a1 e1 fis1:m cis1:m7
		d1 b1:m g1 e1

		% estrofa 4
		a1 e1 fis1:m cis1:m7
		d1 b1:m g1 e1
		e1

		% coro 3
		a1 e1 fis1:m cis1:m7
		d1 d1 a1 e1
		e1

		% coro 4
		a1 e1 fis1:m cis1:m7
		d1 d1 a1 e1
		e1

		% puente
		d1 e1
		d1 e4 e4 r2

		% finale
		a1 e1 fis1:m e1
		a1 e1
		d1:maj7 e1 a1 a1
	}
