	\context ChordNames
		\chords {
		\set Score.markFormatter = #format-mark-box-numbers

		% 1 intro
		\mark \default
		\skip 2*11

		% 2 estrofa 1
		\mark \default
		\skip 2*8

		% 3 estrofa 2
		\mark \default
		\skip 2*9
		\skip 1

		% 4 coro 1
		\mark \default
		\skip 1*9

		% 5 coro 2
		\mark \default
		\skip 1*9

		% 6 interludio
		\mark \default
		\skip 1*8

		% 7 estrofa 3
		\mark \default
		\skip 1*8

		% 8 estrofa 4
		\mark \default
		\skip 1*9

		% 9 coro 3
		\mark \default
		\skip 1*9

		% 10 coro 4
		\mark \default
		\skip 1*9

		% 11 puente
		\mark \default
		\skip 1*4

		% 12 outro
		\mark \default
		\skip 1*10
		}
