\context ChordNames
	\chords {
		\set chordChanges = ##t
		% intro
		a1 e1 fis1:m cis1:m7
		d1 d1:m a1 e1

		% estrofa 1
		a1 e1 fis1:m cis1:m7
		d1 b1:m g1 e1

		% estrofa 2
		a1 e1 fis1:m cis1:m7
		d1 b1:m g1 e1
		e1

		% coro 1
		a1 e1 fis1:m cis1:m7
		d1 d1 a1 e1
		e1

		% coro 2
		a1 e1 fis1:m cis1:m7
		d1 d1 a1 e1
		e1

		% estrofa 3
		a1 e1 fis1:m cis1:m7
		d1 b1:m g1 e1

		% estrofa 4
		a1 e1 fis1:m cis1:m7
		d1 b1:m g1 e1
		e1

		% coro 3
		a1 e1 fis1:m cis1:m7
		d1 d1 a1 e1
		e1

		% coro 4
		a1 e1 fis1:m cis1:m7
		d1 d1 a1 e1
		e1

		% puente
		d1 e1 d1 e1
		e1

		% coro 5
		a1 e1 fis1:m cis1:m7
		d1 d1 a1 e1
		e1

		% coro 6
		a1 e1 fis1:m cis1:m7
		d1 d1 a1 e1
		e1

		% finale
		a1 a1 a1
	}
